<?php

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../lib/Script.php';
require_once __DIR__ . '/../../lib/SmartSieve.lib';

/**
 * Validates that the Sieve code generated by Script::getSieveForRule()
 * is syntactically valid Sieve (RFC 5228).
 *
 * Structural checks always run. If the Dovecot Pigeonhole compiler
 * (sievec) is installed, the generated scripts are additionally
 * compiled with it, which is a full syntax validation.
 */
class SieveGenerationTest extends TestCase
{
    /**
     * Generate a full script (require line + body) from a list of rules,
     * the same way Script::updateScript() assembles it.
     */
    private function buildScript(array $rules): string
    {
        $script = new Script('unittest');
        $script->extensions = array();
        $body = '';
        foreach ($rules as $rule) {
            $body .= $script->getSieveForRule($rule);
        }
        $require = '';
        $started = false;
        foreach ($script->extensions as $ext => $used) {
            if ($used == true) {
                $require .= ($started) ? ',' : 'require [';
                $require .= sprintf('"%s"', $ext);
                $started = true;
            }
        }
        $require .= (strlen($require) > 0) ? "];\n" : '';
        $require .= "\n";
        return $require . $body;
    }

    /**
     * Compile $sieve with sievec if available, otherwise skip silently
     * (structural assertions have already run at this point).
     */
    private function assertCompilesWithSievec(string $sieve): void
    {
        $sievec = trim((string) shell_exec('command -v sievec 2>/dev/null'));
        if ($sievec === '') {
            $this->markTestSkipped('sievec (dovecot-sieve) not installed; skipping compilation check');
        }
        $dir = sys_get_temp_dir() . '/smartsieve-test-' . bin2hex(random_bytes(4));
        mkdir($dir);
        $src = $dir . '/test.sieve';
        file_put_contents($src, $sieve);
        exec(sprintf('%s %s %s 2>&1', escapeshellarg($sievec),
            escapeshellarg($src), escapeshellarg($dir . '/test.svbin')), $output, $rc);
        array_map('unlink', glob($dir . '/*'));
        rmdir($dir);
        $this->assertSame(0, $rc,
            "Generated Sieve failed to compile:\n" . implode("\n", $output) . "\n---\n" . $sieve);
    }

    private function fileintoRule(): array
    {
        return array(
            'status' => 'ENABLED',
            'control' => CONTROL_IF,
            'matchAny' => false,
            'conditions' => array(
                array('type' => TEST_HEADER, 'matchType' => MATCH_CONTAINS,
                      'header' => 'Subject', 'matchStr' => '[SPAM]', 'not' => ''),
                array('type' => TEST_SIZE, 'gthan' => true, 'kbytes' => 500),
            ),
            'actions' => array(
                array('type' => ACTION_FILEINTO, 'folder' => 'INBOX.Spam'),
                array('type' => ACTION_STOP),
            ),
        );
    }

    public function testFileintoRuleGeneratesValidSieve(): void
    {
        $sieve = $this->buildScript(array($this->fileintoRule()));
        $this->assertStringContainsString('require ["fileinto"];', $sieve);
        $this->assertStringContainsString(
            'if allof (header :contains "Subject" "[SPAM]", size :over 500K) {', $sieve);
        $this->assertStringContainsString("\tfileinto \"INBOX.Spam\";", $sieve);
        $this->assertStringContainsString("\tstop;", $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testAddressConditionWithMultipleHeaders(): void
    {
        $rule = array(
            'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => true,
            'conditions' => array(
                array('type' => TEST_ADDRESS, 'matchType' => MATCH_IS,
                      'header' => array('From', 'Sender'),
                      'matchStr' => 'boss@example.com', 'not' => ''),
            ),
            'actions' => array(
                array('type' => ACTION_REDIRECT, 'address' => 'me@example.org'),
            ),
        );
        $sieve = $this->buildScript(array($rule));
        $this->assertStringContainsString(
            'if anyof (address :is ["From","Sender"] "boss@example.com") {', $sieve);
        $this->assertStringContainsString("\tredirect \"me@example.org\";", $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testNegatedConditionAndDiscard(): void
    {
        $rule = array(
            'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
            'conditions' => array(
                array('type' => TEST_HEADER, 'matchType' => MATCH_IS,
                      'header' => 'X-Mailing-List', 'matchStr' => 'dev@example.com',
                      'not' => '1'),
            ),
            'actions' => array(array('type' => ACTION_DISCARD)),
        );
        $sieve = $this->buildScript(array($rule));
        $this->assertStringContainsString(
            'if allof (not header :is "X-Mailing-List" "dev@example.com") {', $sieve);
        $this->assertStringContainsString("\tdiscard;", $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testRejectRule(): void
    {
        $rule = array(
            'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
            'conditions' => array(
                array('type' => TEST_HEADER, 'matchType' => MATCH_CONTAINS,
                      'header' => 'Subject', 'matchStr' => 'lottery', 'not' => ''),
            ),
            'actions' => array(
                array('type' => ACTION_REJECT, 'message' => 'No thank you.'),
            ),
        );
        $sieve = $this->buildScript(array($rule));
        $this->assertStringContainsString('require ["reject"];', $sieve);
        $this->assertStringContainsString("reject text:\nNo thank you.\n.\n;", $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testVacationRuleWithoutCondition(): void
    {
        $rule = array(
            'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
            'conditions' => array(),
            'actions' => array(
                array('type' => ACTION_VACATION, 'days' => 7,
                      'addresses' => array('me@example.org', 'me@example.com'),
                      'message' => "I am away.\nBack on Monday."),
            ),
        );
        $sieve = $this->buildScript(array($rule));
        $this->assertStringContainsString('require ["vacation"];', $sieve);
        $this->assertStringContainsString(
            'vacation :days 7 :addresses ["me@example.org", "me@example.com"] text:', $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testElsifChainGeneratesValidSieve(): void
    {
        $first = $this->fileintoRule();
        $second = array(
            'status' => 'ENABLED', 'control' => CONTROL_ELSEIF, 'matchAny' => false,
            'conditions' => array(
                array('type' => TEST_HEADER, 'matchType' => MATCH_IS,
                      'header' => 'From', 'matchStr' => 'news@example.com', 'not' => ''),
            ),
            'actions' => array(
                array('type' => ACTION_FILEINTO, 'folder' => 'INBOX.News'),
            ),
        );
        $sieve = $this->buildScript(array($first, $second));
        $this->assertStringContainsString(
            'elsif allof (header :is "From" "news@example.com") {', $sieve);
        $this->assertCompilesWithSievec($sieve);
    }

    public function testDisabledRuleGeneratesNothing(): void
    {
        $rule = $this->fileintoRule();
        $rule['status'] = 'DISABLED';
        $script = new Script('unittest');
        $script->extensions = array();
        $this->assertSame('', $script->getSieveForRule($rule));
    }

    public function testMixedScriptCompiles(): void
    {
        $rules = array(
            $this->fileintoRule(),
            array(
                'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
                'conditions' => array(
                    array('type' => TEST_ADDRESS, 'matchType' => MATCH_CONTAINS,
                          'header' => 'From', 'matchStr' => 'noreply@', 'not' => ''),
                ),
                'actions' => array(
                    array('type' => ACTION_FILEINTO, 'folder' => 'INBOX.Robots'),
                    array('type' => ACTION_STOP),
                ),
            ),
            array(
                'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
                'conditions' => array(),
                'actions' => array(
                    array('type' => ACTION_VACATION, 'days' => 3,
                          'addresses' => array(), 'message' => 'Out of office'),
                ),
            ),
            array(
                'status' => 'ENABLED', 'control' => CONTROL_IF, 'matchAny' => false,
                'conditions' => array(),
                'actions' => array(array('type' => ACTION_KEEP)),
            ),
        );
        $sieve = $this->buildScript($rules);
        $this->assertStringContainsString('require ["fileinto","vacation"];', $sieve);
        $this->assertCompilesWithSievec($sieve);
    }
}
